controllers:
    resource: ../src/Controller/
    type: attribute

# accueil

route_accueil:
    path: /accueil
    controller: App\Controller\IndexController::index

# Instrument

instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstruments

# Cours

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours
    
# Responsable

responsableConsulter:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable
responsableLister:
    path: /responsable/lister
    controller: App\Controller\ResponsableController::listerResponsable

# Eleve

eleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve
