controllers:
    resource: ../src/Controller/
    type: attribute

instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstruments

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstruments

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours
    
responsableConsulter:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable

route_accueil:
    path: /accueil
    controller: App\Controller\IndexController::index

