controllers:
    resource: ../src/Controller/
    type: attribute
    
responsableConsulter:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable

route_accueil:
    path: /accueil
    controller: App\Controller\IndexController::accueil

classeInstrumentConsulter:
    path: /classeInstrument/consulter/{id}
    controller: App\Controller\ClasseInstrumentController::consulterClasseInstrument


