controllers:
    resource: ../src/Controller/
    type: attribute

# accueil

route_accueil:
    path: /accueil
    controller: App\Controller\IndexController::accueil

# Instrument

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstruments

# Responsable

responsableConsulter:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable

responsableLister:
    path: /responsable/lister
    controller: App\Controller\ResponsableController::listerResponsable

# Eleve

eleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve

# Classe Instrument

classeInstrumentConsulter:
    path: /classeInstrument/consulter/{id}
    controller: App\Controller\ClasseInstrumentController::consulterClasseInstrument