<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVHG5n4K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVHG5n4K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVHG5n4K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVHG5n4K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVHG5n4K\App_KernelDevDebugContainer([
    'container.build_hash' => 'VHG5n4K',
    'container.build_id' => '4ed5e58c',
    'container.build_time' => 1668434229,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVHG5n4K');
